# Generated by Django 6.0 on 2026-04-06 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('biographie', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('nationalite', models.CharField(blank=True, default='', max_length=100, verbose_name='Nationalité')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('isbn', models.CharField(max_length=17, unique=True, verbose_name='ISBN')),
                ('annee_publication', models.IntegerField(verbose_name='Année de publication')),
                ('categorie', models.CharField(choices=[('roman', 'Roman'), ('essai', 'Essai'), ('poesie', 'Poésie'), ('bd', 'Bande dessinée'), ('science', 'Science'), ('histoire', 'Histoire')], default='roman', max_length=20, verbose_name='Catégorie')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres', to='api.auteur', verbose_name='Auteur')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('tags', models.ManyToManyField(blank=True, related_name='livres', to='api.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['-annee_publication', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True, verbose_name="Date d'emprunt")),
                ('date_retour_prevue', models.DateField(verbose_name='Date de retour prévue')),
                ('rendu', models.BooleanField(default=False, verbose_name='Rendu')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='api.livre', verbose_name='Livre')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-date_emprunt'],
            },
        ),
        migrations.CreateModel(
            name='ProfilLecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('livres_favoris', models.ManyToManyField(blank=True, related_name='fans', to='api.livre', verbose_name='Livres favoris')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil lecteur',
                'verbose_name_plural': 'Profils lecteurs',
            },
        ),
    ]
