# Generated by Django 6.0 on 2026-04-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.CharField(choices=[('roman', 'Roman'), ('essai', 'Essai'), ('poesie', 'Poésie'), ('bd', 'Bande dessinée'), ('bd', 'Developpement'), ('science', 'Science'), ('histoire', 'Histoire')], default='roman', max_length=20, verbose_name='Catégorie'),
        ),
    ]
